-- Foreign key constraints


ALTER TABLE MEMBRE_GROUPE
ADD FOREIGN KEY (id_membre) REFERENCES MEMBRES (id_membre);

ALTER TABLE MEMBRE_GROUPE
ADD FOREIGN KEY (id_groupe) REFERENCES GROUPES (id_groupe);

ALTER TABLE BENEFICIAIRES
ADD FOREIGN KEY (id_regime) REFERENCES REGIME_ALIMENTAIRE (id_regime);

ALTER TABLE DON_PRODUIT
ADD FOREIGN KEY (id_don) REFERENCES DONS (id_don);

ALTER TABLE DON_PRODUIT
ADD FOREIGN KEY (id_produit) REFERENCES PRODUITS (id_produit);

ALTER TABLE PRODUIT_REGIME
ADD FOREIGN KEY (id_produit) REFERENCES PRODUITS (id_produit);

ALTER TABLE PRODUIT_REGIME
ADD FOREIGN KEY (id_regime) REFERENCES REGIME_ALIMENTAIRE (id_regime);

ALTER TABLE COLIS
ADD FOREIGN KEY (id_groupe) REFERENCES GROUPES (id_groupe);

ALTER TABLE COLIS
ADD FOREIGN KEY (id_beneficiaire) REFERENCES BENEFICIAIRES (id_beneficiaire);

ALTER TABLE COLIS_PRODUIT
ADD FOREIGN KEY (id_colis) REFERENCES COLIS (id_colis);

ALTER TABLE COLIS_PRODUIT
ADD FOREIGN KEY (id_produit) REFERENCES PRODUITS (id_produit);

ALTER TABLE DISTRIBUTIONS
ADD FOREIGN KEY (id_colis) REFERENCES COLIS (id_colis);

ALTER TABLE DISTRIBUTIONS
ADD FOREIGN KEY (id_beneficiaire) REFERENCES BENEFICIAIRES (id_beneficiaire);

ALTER TABLE DISTRIBUTIONS
ADD FOREIGN KEY (id_groupe) REFERENCES GROUPES (id_groupe);

ALTER TABLE PRODUIT_BENEFICIAIRES
ADD FOREIGN KEY (id_produit) REFERENCES PRODUITS (id_produit);

ALTER TABLE PRODUIT_BENEFICIAIRES
ADD FOREIGN KEY (id_beneficiaire) REFERENCES BENEFICIAIRES (id_beneficiaire);
